version: '3.7'

services:
  login-ui:
    image: zgate/login-ui:latest
    ports:
      - "3000:80"
    environment:
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433
      - KRATOS_PUBLIC_URL=http://127.0.0.1:4433
    networks:
      - intranet
    restart: on-failure
  admin-ui:
    image: zgate/admin-ui:latest
    ports:
      - "3001:80"
    environment:
      - LOGIN_URL=http://127.0.0.1:4455/auth/login
      - LOGOUT_URL=http://127.0.0.1:4455/auth/logout
    networks:
      - intranet
    restart: on-failure