version: '3.7'

services:
  gateway:
    image: oryd/oathkeeper:v0.38.10-alpine
    ports:
      - "4455:4455"
      - "4456:4456"
    restart: on-failure
    environment:
      - LOG_LEVEL=debug
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    volumes:
      -
        type: bind
        source: ./contrib/gateway
        target: /etc/config/oathkeeper
    networks:
      - intranet
  
  kratos:
    environment: 
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/kratos/public
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=http://127.0.0.1:4455/auth/login
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=http://127.0.0.1:4455/auth/login
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=http://127.0.0.1:4455/auth/settings
      - SELFSERVICE_FLOWS_ERROR_UI_URL=http://127.0.0.1:4455/error
      - SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL=http://127.0.0.1:4455/auth/login
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=http://127.0.0.1:4455/

  login-ui:
    environment: 
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/kratos/public
      - KRATOS_PUBLIC_URL=http://127.0.0.1:4455/kratos/public